### ISSUE TITLE
[469c-RC4] Text breaks and turns to squares after a while of playing on Linux amd64

### ISSUE THREAD

**Issue by Rattle189** [OldUnreal/UnrealTournamentPatches#1080]
Played on ArcoLinux D on 5.19.11-zen1-1-zen kernel with proprietary NVIDIA 515.76 drivers. Text breaks after a while of playing and I have to restart to get it fixed, this issue was also present in Arch Linux (my previous distro). Locale is set to en_US.UTF-8
![Screenshot_20220926_224843](https://user-images.githubusercontent.com/48095450/192308913-2e44bd73-94d9-4b38-9d5e-cc09fa197b3e.png)

**Comment by Rattle189** [comment]
The problem seems to occur on a map change.

**Comment by vide0hanz** [comment]
Confirming this issue as well.

**Comment by stijn-volckaert** [comment]
Could you upload your game logs next time this happens please?

**Comment by vide0hanz** [comment]
Should be noted that I can only reproduce this when using the older OpenGL renderer. Will post a log shortly.

**Comment by vide0hanz** [comment]
> The problem seems to occur on a map change.

I can reliably reproduce this by performing the following steps:

1. Change render device to OpenGLDrv.OpenGLRenderDevice
2. Game > Start Unreal Tournament
3. Escape to menu
4. Game > Start Unreal Tournament
5. Escape to menu

After step 3, you will notice some transparent boxes behind the various singleplayer ladder selections:

![Shot00001](https://user-images.githubusercontent.com/59800033/197420503-56806a7e-1b3e-4526-8d86-58a4f1e3a649.png)

Then, upon going back to the menu the fonts will look exactly like @Rattle189 's screenshot:

![Shot00003](https://user-images.githubusercontent.com/59800033/197420456-ac92aa52-36c4-4e2b-b6d8-d8d514766685.png)

When GUI scaling is active, it becomes more usable at least:

![Shot00002](https://user-images.githubusercontent.com/59800033/197420485-29e36949-fc48-4174-b641-60c0ae0beb3f.png)

Interestingly, when this bug is is doing its thing, it has another effect on transparent textures such as the weapon crate in dm-tutorial:

![Shot00000](https://user-images.githubusercontent.com/59800033/197420600-8af3bf28-a333-4b14-b66c-0300ec3e5781.png)

I do not get any of these issue with XOpenGL. Hope this helps.

**Comment by vide0hanz** [comment]
Here are my OpenGL settings, as requested via the discord:

```
[OpenGLDrv.OpenGLRenderDevice]
VolumetricLighting=False
ShinySurfaces=True
Coronas=True
HighDetailActors=True
DetailTextures=True
NoAATiles=True
NumAASamples=4
UseAA=True
SmoothMaskedTextures=False
UseShaderGamma=True
FrameRateLimit=0
UseMultiDrawArrays=True
UseDrawGouraud469=True
ShaderAlphaHUD=True
DetailMax=2
RefreshRate=0
MaxAnisotropy=0
Use16BitTextures=False
UseHDTextures=True
UseTrilinear=True
UsePrecache=True
UsePalette=True
OneXBlending=False
GammaCorrectScreenshots=False
GammaOffsetBlue=0.000000
GammaOffsetGreen=0.000000
GammaOffsetRed=0.000000
GammaOffset=0.100000
```

**Comment by stijn-volckaert** [comment]
Could you try setting UseAA to false?

**Comment by vide0hanz** [comment]
> Could you try setting UseAA to false?

That seems to be the culprit. Setting this to false resolves everything I mentioned before.

**Comment by stijn-volckaert** [comment]
[OpenGLDrv.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/9893451/OpenGLDrv.zip)

This should fix the problem

**Comment by vide0hanz** [comment]
Seems this issue is back again even with the updated OpenGLDrv.so file.
