### ISSUE TITLE
[469c] OpenGL render scale/pan textures inconsistently to other renders

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#1243]
Reproduce:
1. Load in UnrealEd [Skybox2048_3.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/11359841/Skybox2048_3.zip)
2. Look in perspective view to bottom corners of rainbow cube, when render OpenGL.

Expected result: There appear mismatches, like in other renders:
![scr_1682792845](https://user-images.githubusercontent.com/70026933/235318495-1ceb8c64-2ae5-43fa-8ab7-e25ba0dcde63.png)
![scr_1682792857](https://user-images.githubusercontent.com/70026933/235318496-c730c082-ad41-4713-9e66-6aaffa377d2b.png)
![scr_1682792869](https://user-images.githubusercontent.com/70026933/235318498-bc932fda-a718-4de9-857d-73098e9aca6e.png)
Actual result: there no any mismatches:
![scr_1682792885](https://user-images.githubusercontent.com/70026933/235318514-96143258-a0c9-4f62-ac51-9efd3c27dbc6.png)

Surfaces on this corner:
![scr_1682792988](https://user-images.githubusercontent.com/70026933/235318571-d8be8a42-3529-4b51-bde0-70b0dabf4960.png)
![scr_1682792994](https://user-images.githubusercontent.com/70026933/235318572-4a603230-d411-4bdb-971f-b13d91c42b13.png)
![scr_1682793000](https://user-images.githubusercontent.com/70026933/235318573-224d61ee-14c9-45b2-831b-78e8d52008b3.png)

**Comment by stijn-volckaert** [comment]
Is this still happening? @CacoFFF fixed a similar issue very recently

**Comment by SeriousBuggie** [comment]
Still happening in Preview 8 based builds.

**Comment by SeriousBuggie** [comment]
Fixed in v469d preview 10.

**Comment by CacoFFF** [comment]
Note, this issue still persists if we're running OpenGL in GL 2.1 ARB mode. (aka: compatibility)

**Comment by SeriousBuggie** [comment]
Confirmed. I change ContextType
![img](https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/0d348598-cc48-445d-b633-424148718b4c)
and now issues appear again.
