### ISSUE TITLE
[469b] Possible bug with kickers not boosting the player powerfully enough

### ISSUE THREAD

**Issue by dizzy-egg** [OldUnreal/UnrealTournamentPatches#225]
In the BunnyTrack map [CTF-BT-Chantry.unr](http://www.ut-files.com/index.php?dir=Maps/BunnyTrack/&file=CTF-BT-Chantry.zip), at the very end of the map there is a large/tall cylindrical flag room with the flag at the top. 

I set a checkpoint at the following location:
`Loc="4440.220215,-3276.496338,-7364.84082"`

To reach the flag the player jumps into a pit containing a kicker. The kicker boosts the player up to the top of the room.

**On UT server v451, client v469b:** The kicker (usually) boosts the player high enough to reach the top.

**On UT server v469b, client v469b:** The kicker does not boost the player high enough and the player cannot touch the flag. 

I am not 100% sure if this is a patch-related issue because players have sometimes reported that the map is generally quite buggy anyway, but certainly using v451 enabled me to pass the room properly, whereas using 469b I could not.

**See also:** [[469b] Kicker boosting player far too powerfully #228](https://github.com/OldUnreal/UnrealTournamentPatches/issues/228)

**Comment by dizzy-egg** [comment]
See also: [Issue 228:  [469b] Kicker boosting player far too powerfully #228](https://github.com/OldUnreal/UnrealTournamentPatches/issues/228)

**Comment by CacoFFF** [comment]
Does it still happen if the framerate is limited to 60?

**Comment by dizzy-egg** [comment]
> Does it still happen if the framerate is limited to 60?

No. Limited to 60 and it works properly then. Can it be fixed for higher framerates too please?

**Comment by dizzy-egg** [comment]
Any updates on this issue, please @stijn-volckaert @CacoFFF ?

On v469c (both client and server) this is still a problem.

Just ran into it on a different map: `BT-Vertige-PinkEdition` (the kicker near the very start).

**Comment by stijn-volckaert** [comment]
We've fixed a few kicker problems in 469d. Would you mind testing the latest preview please?

**Comment by SeriousBuggie** [comment]
Still not fixed. Even not need net play.  It not work even on local play.

Reproduce:
1. Start local play altered version: [CTF-BT-Chantry_.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/11714083/CTF-BT-Chantry_.zip)
2. Jump into hole in the floor.

Expected result: Kickers kick you up to ceiling teleporter.
Actual result: Kicker not able kick you up good enough and you bouncing in the air, not able reach next kicker.

Set `fps 60` fix issue. but even `fps 120` enough for return it back. I even not talk about fps like 400 or more.

**Comment by stijn-volckaert** [comment]
Bug confirmed, but we cannot fix this without a fundamental redesign of UE1's physics. Such a redesign would would irreversibly break network compatibility, so we cannot work on this. 

FYI: This map does the exact same thing on 436. At low frame rates (~60 FPS), you get enough boost momentum to reach the ceiling teleporter. At higher fps, you cannot reach the invisible kicker in mid-air.

**Comment by stijn-volckaert** [comment]
Note: this is the same bug as #367. We applied a mitigation for that one, but even tuning the parameters of our mitigation cannot fix this map for higher-fps players

**Comment by dizzy-egg** [comment]
> Note: this is the same bug as #367. We applied a mitigation for that one, but even tuning the parameters of our mitigation cannot fix this map for higher-fps players

Thanks for working on this anyway.

A few questions:

1. What's the underlying cause - is UT physics tied to the framerate somehow?
2. Do you have a recommendation as to the maximum FPS we should be using before things start to break?
3. Does this mean players with a lower FPS have an unfair advantage over players with high FPS?

**Comment by SeriousBuggie** [comment]
1. Engine use float internally. So when FPS goes high, numbers goes wild, because rounding errors make bigger influence.
2. I think it situation dependent. Usually 60 FPS. In some cases it can be even less. For example on map above, first kicker need 95 FPS or less for reach second, when second need 80 FPS or less for reach third.
3. Yes. Also this mean players with variable fps, which can vary by intention, can make more advantage from both. it can be done even via external things, which no any cheat engine able track. you can't kick users just because they have floating fps in general.
4. First of all - mappers must test maps on different FPS. esp which operate on edge of possibility what player can do. Normally exist some gap, so even if you not jump long enough you still reach target. In BT such stuff pushed on edge, and gap really small. Or make 90 from 100 or die.
Also mappers must be aware of such issues and pay more attention to places where involved high speeds. Usually this means jumps of all kinds, include kickers and boots, and movement with movers.
Possible there can be developed safe kickers. I not know about such. But in theory such possible. Such kicker must spawn helper actor, which track each launched player and correct velocity during time if it goes in wrong direction.
Without such actors, make big enough gap of desired results and not try play with edge cases. Use different stuff for challenge.
