### ISSUE TITLE
[469b] Kicker boosting player far too powerfully

### ISSUE THREAD

**Issue by dizzy-egg** [OldUnreal/UnrealTournamentPatches#228]
On BunnyTrack map [CTF-BT-RookCB](http://www.ut-files.com/index.php?dir=Maps/BunnyTrack/&file=CTF-BT-RookCB.zip) there is a kicker which is designed to kick the player forward through an open doorway.

Checkpoint at the location: `Loc="882.374634,3271.444336,-5908.200195"`

**On server v451, client v469b:** The kicker kicks the player forward gently.

**On server v469b, client v469b:** The kicker is vastly overpowered and kicks the player much too strongly. I particularly notice this when I dodge into the kicker (rather than simply run into it).

**Video:** https://streamable.com/pe8vu4

**See also:** [[469b] Possible bug with kickers not boosting the player powerfully enough #225](https://github.com/OldUnreal/UnrealTournamentPatches/issues/225)

**Comment by stijn-volckaert** [comment]
This one should also be fixed in 469d. Can you test the latest preview please?

**Comment by SeriousBuggie** [comment]
Still not fixed. Locally play fine, but on net top kicker push too hard on high fps.

Reproduce:
1. Start on dedic server [CTF-BT-RookCB_.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/11714119/CTF-BT-RookCB_.zip)
2. After respawn just walk forward into button at end
![img](https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/9f94f68b-8083-4a38-9629-f371eaf9e54f)
Kicker kick you up. Kicker on top kick you back. You must land near place for door (i remove door for simplicity).

Expected result: You always land near door, not far more. it independent from FPS. Land place match for local play.
Actual result: Even with limit to 30 FPS it can push near twice more far. At 60 FPS it happen much often. On 300-400 FPS - it push so hard so you fly away from second floor.

**Comment by dizzy-egg** [comment]
Link to more discussion: https://github.com/OldUnreal/UnrealTournamentPatches/issues/225#issuecomment-1586104310

**Comment by stijn-volckaert** [comment]
This one will be fixed in 469d
