### ISSUE TITLE
[win][469a] Software render not list good resolutions in windowed mode

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#57]
Almost all resolutions in list is 4:3.
![scr_1601293500](https://user-images.githubusercontent.com/70026933/94428331-370aa280-0199-11eb-87e7-148261869b02.png)

**Comment by stijn-volckaert** [comment]
This will also be fixed in 469b

**Comment by gargul2** [comment]
I confirm.

**Comment by SeriousBuggie** [comment]
![screen](https://user-images.githubusercontent.com/70026933/98248807-1d216400-1f7e-11eb-940d-46f914964652.png)
Not fixed in v469b.

**Comment by stijn-volckaert** [comment]
This is the default resolutions list. To see the actual supported resolutions for SoftDrv, you need to enable DirectDraw. I can force-enable that for people who use SoftDrv if you think it's a good idea.

**Comment by SeriousBuggie** [comment]
Maybe better update default resolutions list with common well-known 16:9 resolutions?

**Comment by SeriousBuggie** [comment]
Test with enabled DirectDraw - list all resolutions properly. Also without direct draw UT can not goes fullscreen.
But I do not think we need force change this option.
It must be by default true. But if user disable it, we do not need turn it back. possible it case problems and it hard turn off.

**Comment by SeriousBuggie** [comment]
So final result: Fixed in v469b. Confirmed.
