### ISSUE TITLE
[469b] UZ Decompression fails if the compressed file is bigger than the original file

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#656]
Moved from: https://www.oldunreal.com/phpBB3/viewtopic.php?f=42&t=4511

It turned out old UT (v436 at least) contains bug: https://ut99.org/viewtopic.php?p=122257#p122257
So I suggest add option for v469 - minimal size of file for redirect.
It can be for all clients or only for bugged (I think VER < 469).

IDK which minimal size of U package file which still produce .uz file less or equal size.
But I think not a big deal set default to some value like 8 KB and forget about this.

1-4 KB is not a big difference at all, so search exact border can be useless.

---
I dig into code and realize - server send only packages lists and download managers list.
So server can not say "do not use this manager for this file".

So we can not fix this issue from server v469.

What we can do:
Add warning about crash to UCC compress commandlet.
For example: "This .uz file bigger from original, what cause crash on older UT clients (ver < 469). Better do not use it."
Or maybe deny create such files without special flags at all.

I use next texts in UZ tool:
https://github.com/SeriousBuggie/UZ
```
        allowbad        Allows the creation of .uz files that cause crash on clients below version 469.
```
```
uz compress relicsbindings.u
Compressing relicsbindings.u (582 bytes)
stage 0: 0.000000 secs
stage 1: 0.000000 secs
stage 2: 0.000000 secs
stage 3: 0.000000 secs
Total: 0.000000 secs
Skipped: This .uz file cause crash on clients below 469. Use the 'allowbad' parameter to create this .uz file anyway.
Such files should be the last in the ServerPackages list to avoid speed drops for all subsequent files on older clients.
```

**Comment by garry-ut99** [comment]
> Buggie:
>
> Fixed at least in v469.
> for bugged (I think VER < 469).
> Skipped: This .uz file cause crash on clients below 469.

The bug doesn't seem to be fixed in 469c, either it was never completely fixed at all / fixed partially only, or was fixed in some earlier version of 469, and then reappeared in some newer version of 469. 

Reproduced with [SmartBan mod/mutator](https://ut99.org/viewtopic.php?f=7&t=15554) installed, while a 469c client trying to get `WinClient.u.uz` from a 469c redirect server.

As a workaround I extracted/decompiled `.uc` from `.u`, then edited `.uc` so that it's bigger (for example you can put several comments inside), and then compiled `.uc` again, and then compressed to `.uz` file, which is now smaller than `.u` file and the redirection works now.

Other example is LONDON server, which uses the same SmartBan mod, the `.uz` files are downloaded from the redirection server, until WinClient silently fails because the file is not even present on the redirection server, and then it's downloaded directly from the game server.

**Comment by SeriousBuggie** [comment]
Please attach bugged example of file.

**Comment by garry-ut99** [comment]
I'm curious why do you need it, does that mean you're unable to reproduce the bug on your side by packing `WinClient.u` to `WinClient.u.uz` by yourself, using UCC (either 451 or 469c) or your UZ Tool... 
Anyway: since you've asked: [WinClient.u.uz.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/11240452/WinClient.u.uz.zip) (.zip extension is fake, just remove it).

**Comment by an-eternity** [comment]
UZ Tool won't compress this WinClient.u file unless it is forced by 'allowbad' parameter.

**Comment by SeriousBuggie** [comment]
> > Buggie:
> > Fixed at least in v469.
This mean such files can be decoded in v469. Or in your v469 it not work too?

**Comment by garry-ut99** [comment]
On the both: [releases](https://github.com/OldUnreal/UnrealTournamentPatches/releases) and [ReleaseNotes](https://github.com/OldUnreal/UnrealTournamentPatches/blob/master/ReleaseNotes.md) pages, the first mentioned version of 469 patches family, at the very bottom, is 469a:
- it misled/deceived me into thinking that this section: [Old Release Notes](https://github.com/OldUnreal/UnrealTournamentPatches/blob/master/ReleaseNotes.md#old-release-notes), by "older patches" means patches older than 469 family (which means 468 and older)
- which further misled/deceived me to think that 469a is the first/oldest version of 469 patches family, 
- which further misled/deceived me into thinking that by v469 you meant it's fixed in the whole 469 patches family (in all versions of 469 patches).  

Only now, after your comment, I've viewed "The release notes for older patches released by Epic and UTPG" which can be found in the Help/ReleaseNotes.htm file which is included in the patch, and have discovered that there exists also yet older version of 469 family patches, named v469, and which came before 469a. Now that this misunderstanding has been cleared up, I know that by v469 you meant version v469 and not whole 469 family.

Finally answering the question: I don't know whether v469 is affected or not because I didn't try it.

**Comment by SeriousBuggie** [comment]
Well. When i speak about v469 i mean v469b/c at this point. So more clear answer - in v469c file must decode properly. Which not cancel fact about crash v469a and older clients. 

I even not sure about v469b, because not remember when it be fixed. From ReleaseNotes it goes v469b affected as well.

**Comment by garry-ut99** [comment]
Like I already said: I tested a 469c client on a 469c server and it didn't work, I'm not sure what more information do you want me to provide you, but feel free to ask, meanwhile as for me, I'm curious whether did you reproduce the bug on 469c client + 469c server.

**Comment by SeriousBuggie** [comment]
What exactly not work?

```js
Z:\UT_469c\System>ucc decompress WinClient.u.uz
  = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
 u c c . e x e :   U n r e a l O S   e x e c u t i o n   e n v i r o n m e n t
 C o p y r i g h t   1 9 9 9   E p i c   G a m e s   I n c
 = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =

 E x e c u t i n g   C l a s s   I p D r v . D e c o m p r e s s C o m m a n d l e t
 s t a g e   0 :   0 . 0 0 0 1 1 7   s e c s
 s t a g e   1 :   0 . 0 0 0 0 4 3   s e c s
 U s e d   1 2   t h r e a d s .
 s t a g e   2 :   0 . 0 0 0 8 5 6   s e c s
 s t a g e   3 :   0 . 0 0 0 0 0 9   s e c s
 T o t a l :   0 . 0 0 1 0 2 5   s e c s
 D e c o m p r e s s e d   W i n C l i e n t . u . u z   - >   W i n C l i e n t . u
```

**Comment by garry-ut99** [comment]
> In short: UT contains bug, which cause download only first N bytes of .uz file. Where N is size of uncompressed file. So if compressed file bigger from original, it is downloaded partially and can not be decoded. Fixed at least in v469.

Not fixed, a 469c client, while connecting to a 469c server, and trying to get WinClient.u.uz from redirect server:

> [Client screen] : [Connection failed. Downloading package WinClient failed: Server refused to send WinClient](https://ut99.org/viewtopic.php?f=12&t=15401).
> [Server log] : [Received invalid file request](https://ut99.org/viewtopic.php?t=11469)

Manual decompressing works, but not when connecting to a server.

**Comment by SeriousBuggie** [comment]
You sure it about UZ compression? UT server never send UZ files. It send direct files, if this allowed. UZ files send some HTTP redirect.

So even if there UZ issue it related only to client while connecting. Server there not involved at all.

Also I check on UCC v436 your uz file, it decoded properly. Possible in-game it act different, but in console run it decompress.

**Comment by garry-ut99** [comment]
> You sure it about UZ compression? UT server never send UZ files. It send direct files, if this allowed. UZ files send some HTTP redirect.

Damn it...I do know how a server works, I'm not stupid, it seems it's you who misunderstood my comments, I quote again:

> garry-ut99 : https://github.com/OldUnreal/UnrealTournamentPatches/issues/656#issuecomment-1508801228 : while a 469c client trying to get and extract WinClient.u.uz from a 469c **redirect server**.

> garry-ut99 : https://github.com/OldUnreal/UnrealTournamentPatches/issues/656#issuecomment-1519129975) : and trying to get WinClient.u.uz from **redirect server**:

The .uz file whose decompression fails is hosted on / downloaded from a redirect server, not on a game server.
`AllowDownloads=False` so it's not about .u file from a game server.

> So even if there UZ issue it related only to client while connecting. Server there not involved at all.

I do know, I'm not stupid, I mentioned the server version just in case it was somehow related though, but most likely it is not.

> Also I check on UCC v436 your uz file, it decoded properly. Possible in-game it act different, but in console run it decompress.

I do know, I'm not stupid, it manually decoded properly for me too, but was still failing in-game.
I asked you twice whether you were able to reproduce the ACTUAL issue reported by me, what I reported was: connecting a client to a server, but instead, your repro was: "it works in console for me, so what's the problem?"...you foolishly assumed that if it extracted correctly on console, it would also work in the game, but it is not!

**Comment by stijn-volckaert** [comment]
I tried to reproduce this locally but couldn't. I set up a (mostly vanilla) server that serves downloads from a local redirect server. The gameserver has WinClient in its ServerPackages list. The redirect server serves your WinClient.u.uz.zip file (renamed to WinClient.u.uz).

I tested the 469c release client and the latest 469d preview client. In both cases, the client downloaded the file from the redirect server and decompressed it without any issues.

I'll take a look at the original 436 code next to see what the original problem was

**Comment by garry-ut99** [comment]
The gameserver has WinClient in its ServerPackages list.

I did what SmartBan's manual says, and it doesn't say to put WinClient into ServerPackages list:

<details>
<summary>SPOILER</summary>

> --------------INSTALLATION--------------
> 
> Copy files WinClient.u and sbnXX.u (XX - version mod) to games System folder.
> 
> If using ACE anti-cheat on server copy also:
> IACEv12.u and sbe12.u for ACE1.2x
> IACEv13.u and sbe13.u for ACE1.3x
> 
> UnrealTournament.ini:
> [Engine.GameEngine]
> ServerPackages=sbnXX
> ServerActors=sbnXX.SmartBanActor (or as a mutator: sbnXX.SmartBan)
> 
> After starting the server, the SmartBan.ini file with the mod settings is created in the games System folder.

</details>

But I've added right now WinClient into ServerPackages anyway and then have restarted server but it has make no difference, still fails when trying to connect.

**Comment by stijn-volckaert** [comment]
Bug confirmed. This is not fixed in any of the 469 versions. Here's what happens:

- IpDrv.HTTPDownload downloads the full file but only saves its first X bytes, where X is the original (uncompressed) file size
- The game then tries to decompress the truncated file
- 436 crashes during decompression. 469 (up to and including the March previews of 469d) silently fails to decompress
- 469 then redownloads the file directly from the server, if the server supports Engine.ChannelDownload downloads
- 469 receives the original file and installs it

**Comment by stijn-volckaert** [comment]
Fix pushed for the next 469d preview

**Comment by SeriousBuggie** [comment]
Oh. Another bug here. Initially v436 crash because allocate wrong buffer size. it be fixed. Not know about downloading issue.

Good to know, it finally resolved.

**Comment by SeriousBuggie** [comment]
But this still not touch original reason of open issue - warn users who compress files, about such problematic files. Because current fix solve issue only for new clients. Old clients still can crash (v436) or not able get file (prior v469d).

So possible need consider add warning, as suggested in first post.

**Comment by an-eternity** [comment]
That fix should have been tested with direct downloads turned off yet a long time ago. Looks like none of the testers did it...

> So possible need consider add warning, as suggested in first post.

Most admins unlikely read warnings...
I think, the way UZ tool handles this case is the most optimal solution.
