### ISSUE TITLE
[469a] Small XOpenGL issue

### ISSUE THREAD

**Issue by J3FFmaster** [OldUnreal/UnrealTournamentPatches#87]
![Unreal Tournament Screenshot 2020 10 05 - 00 31 17 49](https://user-images.githubusercontent.com/72396328/95087387-e6a7bd80-0721-11eb-9854-5c105d30caf3.png)

Those black bars only appear when using XOpenGL (as D3D seems fine).

**Comment by stijn-volckaert** [comment]
Are you using the default textures or some high-resolution texture pack?

**Comment by J3FFmaster** [comment]
Default, 32bit.

**Comment by Chamberly** [comment]
I also got the same. XOpenGL, 32bit color depth, default textures. My setting may be a tinny bit different from the default.
![image](https://user-images.githubusercontent.com/11419314/95143221-7e69d380-0743-11eb-841f-ea1df1ab22b4.png)

**Comment by J3FFmaster** [comment]
Yeah, it's not you or me, it's the renderer. 
As I had also asked other friends to confirm this behavior before I posted this.

**Comment by stijn-volckaert** [comment]
Fixed for 469b.

**Comment by SeriousBuggie** [comment]
Not test this before for say exists it for me or no, but tested now - all look fine:
![screen](https://user-images.githubusercontent.com/70026933/98253615-ecdcc400-1f83-11eb-9f93-fd54a523ec76.png)

**Comment by joranm1** [comment]
Just tried with last git revision on Linux, the issue is not fixed...

**Comment by stijn-volckaert** [comment]
469b is not on github yet. You can only get it through the oldunreal beta forum. We will push 469b to github soon
