### ISSUE TITLE
[469c-RC2] [macOS] - Screen goes black when changing resolution via the menu

### ISSUE THREAD

**Issue by shinra-electric** [OldUnreal/UnrealTournamentPatches#976]
Running 469c-RC2 on an M1 and an external 2560x1440 Thunderbolt display. 

When I try to select 1440p from the options menu, the screen goes black. I assume there is a "Click ok if you can see this" dialog, but I can't see it. 

I can revert to the previous resolution by hitting esc several times.

**Comment by stijn-volckaert** [comment]
Should be fixed in RC3

**Comment by Swiss-Mac-User** [comment]
I have the same issue still with 469d.

What works:
* Click `Alt`+`Return` to exit fullscreen
* Click the "Zoom Window" (green bubble) on the UT window
* Now Fullscreen works without the black overlay

Had to manually fiddle with the `UnrealTournament.ini`, e.g. add my desired fullscreen resolution there and other graphics settings. **This helped to get rid of the behaviour** - but I don't recall which setting exactly it was.
